spring.application.name=enotes-api-service

# database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/enotes_dev
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.datasource.username=postgres
spring.datasource.password=airforce
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
# this is preferred at industry level, not create or update
spring.jpa.hibernate.ddl-auto=none                         
